# -*- coding: utf-8 -*-
"""Trends_annual_rainfall22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXBkIU6add7jzPdo_ADquiK98JR7qKIC
"""

!pip install pymannkendall

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pymannkendall as mk

from google.colab import files
uploaded = files.upload()

file = "All in one2 .xlsx"
df = pd.read_excel(file)

df.head()

file = "All in one2 .xlsx"
df = pd.read_excel(file)
df['Date'] = pd.to_datetime(df['Date'], unit='D', origin='1899-12-30', errors='coerce')

df['Date'].min(), df['Date'].max()

df.columns

"""Annual Trend Analysis
Annual Rainfall
"""

df_indexed = df.set_index('Date')
annual = df_indexed.resample('YE').mean()

annual.head()

result = mk.original_test(annual['Bishoftu_Precip'])

print(result)

df_indexed = df.set_index('Date')
annual = df_indexed.resample('YE').mean()

stations = ['Bishoftu_Precip','Bole_Precip','Mojo_Precip','Obs_Precip','Akaki_Precip','Sendafa_Precip','Ginchi_Precip','Hombole_Precip']

trend_result = []

for station in stations:
    result = mk.original_test(annual[station])
    trend_result.append([station, result.trend, result.p, result.slope, result.z])

trend_df = pd.DataFrame(trend_result,
                        columns=['Station','Trend','P-value','Sen Slope', 'Z-value'])

trend_df

result = mk.original_test(annual['Bishoftu_Precip'])

print("Z value:", result.z)
print("P value:", result.p)

if result.p < 0.01:
    print("Significant at 99% level")
elif result.p < 0.05:
    print("Significant at 95% level")
elif result.p < 0.10:
    print("Significant at 90% level")
else:
    print("Not significant")

stations = [
    'Bishoftu_Precip',
    'Bole_Precip',
    'Mojo_Precip',
    'Akaki_Precip',
    'Ginchi_Precip',
    'Hombole_Precip',
    'Obs_Precip',
    'Sendafa_Precip'
]

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import matplotlib.dates as mdates
import matplotlib.ticker as ticker # Import ticker module

# Assuming df, df_indexed, annual, and stations are already defined from previous cells

min_date_annual = annual.index.min()
max_date_annual = annual.index.max()

for station in stations:
    station_name_display = station.replace('_Precip', '')

    plt.figure(figsize=(10, 6))

    # Plot the annual data
    plt.plot(annual.index, annual[station], marker='o', linewidth=1, label=station_name_display, color='skyblue')

    # Add a trend line using seaborn.regplot
    # Convert date index to numerical format for regplot
    x_numeric = mdates.date2num(annual.index.to_pydatetime())
    sns.regplot(x=x_numeric, y=annual[station], ax=plt.gca(), scatter=False, color='red', line_kws={'linestyle':'--'}, label='Trend Line')

    plt.title(f"Annual Rainfall Trend - {station_name_display} (1985–2014)", fontsize=14)
    plt.xlabel("Year", fontsize=12)
    plt.ylabel("Annual Rainfall (mm)", fontsize=12)
    plt.grid(True, alpha=0.3)

    # Set x-axis limits to match the data range
    plt.xlim(min_date_annual, max_date_annual)

    # Generate ticks for every 5 years from 1985 to 2014, ensuring 1985 is included
    start_year = min_date_annual.year
    end_year = max_date_annual.year
    major_tick_years = list(range(start_year, end_year + 1, 5))
    if start_year not in major_tick_years:
        major_tick_years.insert(0, start_year)

    # Align tick dates with the 'End of Year' nature of the annual index
    major_tick_dates = [pd.Timestamp(f'{year}-12-31') for year in major_tick_years]
    plt.gca().xaxis.set_major_locator(ticker.FixedLocator(mdates.date2num(major_tick_dates))) # Use ticker.FixedLocator

    # Format x-axis to display years
    formatter = mdates.DateFormatter('%Y')
    plt.gca().xaxis.set_major_formatter(formatter)

    plt.xticks(rotation=45, ha='right') # Apply rotation to the formatted labels

    plt.legend(fontsize=10)
    plt.tight_layout()
    plt.show()